### ISSUE TITLE
Tournament Experience

### ISSUE THREAD

**Issue by DJam98** [LeptoSpira/rw-offthedialbot#16]
Ability to gain experience points. Placements would earn points as well as participation. Certain levels would earn roles. Tournaments such as IDTGA would earn more experience than something like the Special Series. The experience points could be distributed manually by organisers or automatically.

**Comment by LeptoSpira** [comment]
I can incorporate that into the ELO actually, simply add about 10 points per tournament entered, and tournament experience can add from 10 to 200 points maybe.
